// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whfravepyelgvgveuwfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZnJhdmVweWVsZ3ZndmV1d2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTYzNzgsImV4cCI6MjA2ODU5MjM3OH0.HcgNmuvNzveqpPsps5Z5gRQwmSTD6bpuP8_McMHWEOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});